# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 0

# Personal info
name: Serena Santi
title: Ph.D. Student in Wireless Communication
email: serenasanti@gmx.com

# Dark Mode (true/false/never)
darkmode: never

# Social links
github_username:  ssi15004
linkedin_username: santiserena
orcid_username: 0000-0002-3232-5040

additional_links:
- title: ResearchGate
  icon: fab fa-researchgate
  url: https://www.researchgate.net/profile/Serena-Santi

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs

  Ever since high school I was very interested in the study of computer science in general, and computer networks and embedded systems in particular, mainly due to the many existing open research challenges and a lot of interesting applications in these areas. 
  I first began the study of computer science in high school because I wanted to understand more the functioning of the computers, both from the software that the hardware perspective. 
  After graduation, I chose the faculty of Computer Science at the University of Camerino to pursue a bachelor and master degree, in line with my high school diploma. 
  I had classes oriented mainly towards theoretical computer science. 
  During my bachelors I followed classes on algorithms and data structures, logics, calculus, numerical analysis, statistics and operational research. 
  Coherent with my bachelor education, I further deepened my theoretical knowledge during my masters. 
  I followed courses such as model checking, theory of complexity, and modelling and simulation.

  Wanting to gain some more practical computer science knowledge, I took the opportunity to go on Erasmus during my masters. 
  I went to Mälardalen University in Sweden to immerse myself into one of my original passions, embedded systems design. 
  I followed several courses that were not available in my own university, about scheduling and management of real time embedded systems. 
  Being abroad, and studying in a more practical research-oriented environment, the idea to pursue a PhD started growing in my mind.

  As such, I was very happy when I stumbled upon an open research position at the University of Antwerp during Summer 2016, to investigate heterogeneous low-power wireless communications protocols for Internet of Things (IoT) devices. 
  I discovered that IoT research finds itself on the intersection between embedded systems, wireless communications, and data analytic, which perfectly aligns with my original passions.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Harvard University
        caption: 2010 - 2013
        sub_title: BSc Computer Science
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
